# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:flutter_teg_code_style/*.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
#   exclude:
#     - path/to/excluded/files/**
