name: flutter_code_style
description: Darel bitsy's flutter code style for application and libraries that focus on dart best pratices.
version: 2.1.1
repository: https://github.com/bitsydarel/flutter-code-style
issue_tracker: https://github.com/bitsydarel/flutter-code-style/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
