name: flutter_code_style
description: Darel bitsy's flutter code style for application and libraries that focus on dart best pratices.
version: 1.6.8
homepage: https://github.com/bitsydarel/flutter-code-style
author: darelbitsy <bitsydarel@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'
