name: flutter_code_style
description: Darel bitsy's flutter code style for application and libraries that focus on dart best pratices.
version: 2.0.2
homepage: https://github.com/bitsydarel/flutter-code-style

environment:
  sdk: '>=2.4.0 <3.0.0'
